os_version:             # example of possible values
  - linux_64: alma8
  - linux_aarch64: alma8
  - linux_ppc64le: alma8
  

c_compiler:
  - gcc                        # [linux]
  - clang                      # [osx]
  - vs2022                     # [win]

c_stdlib:
  - sysroot                    # [linux]
  - macosx_deployment_target   # [osx]
  - vs                         # [win]

c_stdlib_version:              # [unix]
  - 2.34                       # [linux]
  - 10.13                      # [osx and x86_64]
  - 11.0                       # [osx and arm64]

