{% set version = "2025_06_11" %}
{% set sha256  = "a2f90542551ae602d8c02a4d8f07c6549d39e5a0ca097219a2efede297faab9a" %}

package:
  name: passt
  version: {{ version }}

source:
  url: https://passt.top/passt/snapshot/passt-2025_06_11.0293c6f.tar.gz
  sha256: {{ sha256 }}

build:
  skip: True  # [win or win_64 or osx or osx_64]
  number: 0
  script: |
    make
    install -Dm755 passt "${PREFIX}/bin/passt"
    install -Dm755 pasta "${PREFIX}/bin/pasta"
    install -Dm644 passt.1 "${PREFIX}/share/man/man1/passt.1"
    install -Dm644 pasta.1 "${PREFIX}/share/man/man1/pasta.1"

requirements:
  build:
    - {{ compiler('c') }}
    - {{ stdlib('c') }}
    - make
    - kernel-headers_linux-64 >=5.14.0

test:
  commands:
    - passt --help \| head -n 5
    - pasta --version
    - pasta --help \| head -n 5

about:
  home: https://passt.top/passt/about/
  license: GPL-2.0-or-later
  license_file:
    - LICENSES/GPL-2.0-or-later.txt
    - LICENSES/BSD-3-Clause.txt
  summary: "passt: Plug A Simple Socket Transport/pasta: Pack A Subtle Tap Abstraction"

extra:
  recipe-maintainers:
    - 2themaxx
