{% set version = "2025_06_11" %}
{% set sha256 = "a2f90542551ae602d8c02a4d8f07c6549d39e5a0ca097219a2efede297faab9a" %}

package:
  name: passt
  version: {{ version }}

source:
  url: https://passt.top/passt/snapshot/passt-{{ version }}.0293c6f.tar.gz
  sha256: {{ sha256 }}

build:
  number: 0
  skip: true  # [win]

requirements:
  build:
    - {{ compiler('c') }}
    - {{ stdlib("c") }}  # [not (linux and x86_64)]
    - pkg-config
  host:
    - glib
    - libseccomp
  run:
    - glib
    - libseccomp

test:
  commands:
    - passt --version

about:
  home: https://passt.top/passt/
  license: GPL-2.0-or-later
  license_family: GPL
  license_file: COPYING
  summary: "A socket passthrough application for slirp-free network access in containers and VMs"
  description: |
    passt (Port-forwarding socket tool) is a tool to let applications in
    separate namespaces access the network without full privileges or slirp.
  dev_url: https://passt.top/passt/

extra:
  recipe-maintainers:
    - 2themaxx
