{% set name = "reactpy-router" %}
{% set version = "1.0.1" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.org/packages/source/{{ name[0] }}/{{ name }}/reactpy_router-{{ version }}.tar.gz
  sha256: b7931b40b7b5e98e83fe8184eeae208e1ffab04530d9aaf524d6c09c5ee75e72

build:
  noarch: python
  script: {{ PYTHON }} -m pip install . -vv --no-deps --no-build-isolation
  number: 0

requirements:
  host:
    - python >=3.9
    - hatchling
    - hatch-build-scripts
    - pip
  run:
    - python >=3.9
    - reactpy >=1.0.0
    - typing_extensions

test:
  imports:
    - reactpy_router
  commands:
    - pip check
  requires:
    - pip

about:
  summary: A URL router for ReactPy.
  dev_url: https://github.com/reactive-python/reactpy-router
  license: MIT
  license_file: LICENSE.md

extra:
  recipe-maintainers:
    - shawncrawley
