{% set name = "erddapcfg" %}
{% set version = "0.0.2" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.org/packages/source/{{ name[0] }}/{{ name }}/erddapcfg-{{ version }}.tar.gz
  sha256: 4e890acf8605970d28d0666b7dfff75c1fa3029e1ab8db69154e88d89547e444

build:
  entry_points:
    - erddapcfg=erddapcfg.cli:cli_entry_point
  noarch: python
  script: {{ PYTHON }} -m pip install . -vv --no-deps --no-build-isolation
  number: 0

requirements:
  host:
    - python {{ python_min }}
    - pip
  run:
    - python >={{ python_min }}
    - pandas
    - jinja2

test:
  imports:
    - erddapcfg
  commands:
    - pip check
    - erddapcfg --help
  requires:
    - python {{ python_min }}
    - pip

about:
  home: https://github.com/PlehanSebastian/erddapcfg
  summary: Python program to work with ERDDAP configurations.
  license: MIT
  license_file: LICENSE

extra:
  recipe-maintainers:
    - ocefpaf
