context:
  name: "scope"
  version: "0.6.3"
  python_min: "3.10"

package:
  name: ${{ name|lower }}
  version: ${{ version }}

source:
  url: https://pypi.org/packages/source/${{ name[0] }}/${{ name }}/${{ name }}-${{ version }}.tar.gz
  sha256: 0230861e4d2bd7cc11890c33adffbb2e9b9d1899975a44984de745972002992a

build:
  noarch: python
  script: python -m pip install . -vv --no-deps --no-build-isolation
  number: 0

requirements:
  host:
    - python ${{ python_min }}.*
    - setuptools
    - pip
  run:
    - python >=${{ python_min }}
    - av
    - elements >=3.16.6
    - fastapi
    - mediapy
    - numpy
    - orjson
    - pillow
    - uvicorn

tests:
  - python:
      imports:
        - scope
      python_version: ${{ python_min }}.*

about:
  homepage: http://github.com/danijar/scope
  summary: Metrics logging and analysis
  license: MIT
  license_file: LICENSE

extra:
  recipe-maintainers:
    - noahjutz
