{% set name = "ecco_access" %}
{% set version = "0.2.0" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.org/packages/source/{{ name[0] }}/{{ name }}/ecco_access-{{ version }}.tar.gz
  sha256: 04b7782bbcc0cfca9269577ed5041fe7e9c6949108eedb3cad6e50087c8650e2

build:
  noarch: python
  script: {{ PYTHON }} -m pip install . -vv --no-deps --no-build-isolation
  number: 0

requirements:
  host:
    - python >=3.7
    - setuptools >=80
    - wheel
    - setuptools-scm >=8.0
    - pip
  run:
    - python >=3.7
    - numpy
    - future
    - dask-core
    - fsspec >=2024.12.0
    - netcdf4
    - pandas
    - python-dateutil
    - requests
    - s3fs >=2024.12.0
    - tqdm
    - xarray
    - zarr >=3.0.7
    - pyresample

test:
  imports:
    - ecco_access
  commands:
    - pip check
  requires:
    - pip

about:
  home: https://github.com/ECCO-GROUP/ECCO-ACCESS/tree/main/ecco_access
  summary: Access utilities for ECCO state estimate output hosted on PO.DAAC and in the AWS cloud
  license: MIT
  license_file:
    - LICENSE

extra:
  recipe-maintainers:
    - andrewdelman
