{% set name = "reactpy-django" %}
{% set version = "5.0.0" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.org/packages/source/{{ name[0] }}/{{ name }}/reactpy_django-{{ version }}.tar.gz
  sha256: 5a930de7272e27d97e39b619583077af741bc19343e265e3fe8da6d876d31d84

build:
  skip: true

requirements:
  host:
    - python >=3.9
    - setuptools >=42
    - wheel
    - pip
  run:
    - python >=3.9
    - channels >=4.0.0
    - django >=4.2.0
    - reactpy <1.1.0,>=1.0.2
    - reactpy-router <2.0.0,>=1.0.0
    - dill >=0.3.5
    - orjson >=3.6.0
    - nest-asyncio >=1.5.0
    - typing_extensions

test:
  imports:
    - js
    - reactpy_django
  commands:
    - pip check
  requires:
    - pip

about:
  home: https://github.com/reactive-python/reactpy-django
  summary: It's React, but in Python. Now with Django integration.
  license: MIT
  license_file: LICENSE.md

extra:
  recipe-maintainers:
    - shawncrawley
