schema_version: 1

context:
  name: streamlit-code-editor
  version: 0.1.22

package:
  name: ${{ name|lower }}
  version: ${{ version }}

source:
  url: https://pypi.org/packages/source/${{ name[0] }}/${{ name }}/streamlit-code-editor-${{ version }}.tar.gz
  sha256: 93e6ecb4060614bce99eaf758b4cb5c8ce2accc0eb5140cbbb23c05cb4e9d7f6

build:
  number: 0
  noarch: python
  script: 
   # This small doc is not part of the sdist, just skip for now.
   - touch PROJECT.md
   - ${{ PYTHON }} -m pip install . -vv --no-deps --no-build-isolation

requirements:
  host:
    - python ${{ python_min }}.*
    - pip
    - setuptools
  run:
    - python >=${{ python_min }}
    - streamlit >=0.63

tests:
  - python:
      python_version: ${{ python_min }}.*
      imports:
        - code_editor
      pip_check: true

about:
  summary: React-ace editor customized for Streamlit
  license: MIT
  license_file: LICENSE
  homepage: https://github.com/bouzidanas/streamlit-code-editor

extra:
  recipe-maintainers:
    - xhochy
