{% set name = "tsdisagg" %}
{% set version = "1.3.1" %}
{% set python_min = "3.11" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.org/packages/source/{{ name[0] }}/{{ name }}/tsdisagg-{{ version }}.tar.gz
  sha256: fbd64abc589795ed78387fedf3e066d467caae42adf710e9da17cbe51e49eb80

build:
  noarch: python
  script: {{ PYTHON }} -m pip install . -vv --no-deps --no-build-isolation
  number: 0

requirements:
  host:
    - python {{ python_min }}
    - pip
    - hatchling
    - hatch-vcs
  run:
    - python >={{ python_min }}
    - numpy
    - pandas >=2.2.0
    - scipy

test:
  imports:
    - tsdisagg
  commands:
    - pip check
  requires:
    - pip
    - python {{ python_min }}

about:
  home: https://github.com/jessegrabowski/tsdisagg
  summary: Temporal Disaggregation of Time Series Data in Python
  license: MIT
  license_file: LICENSE

extra:
  recipe-maintainers:
    - jessegrabowski
