context:
  name: "ninjax"
  version: "3.6.2"

package:
  name: ${{ name|lower }}
  version: ${{ version }}

source:
  url: https://pypi.org/packages/source/${{ name[0] }}/${{ name }}/${{ name }}-${{ version }}.tar.gz
  sha256: 3eabc014d94d05177f3ade206dc43a7503cb130eb6d396da73eb607b5c20054a

build:
  skip:
    - win
  script: ${{ PYTHON }} -m pip install . -vv --no-deps --no-build-isolation
  number: 0

requirements:
  host:
    - python
    - setuptools
    - pip
  run:
    - python
    - jax


tests:
  - python:
      imports:
        - ninjax

about:
  homepage: http://github.com/danijar/ninjax
  summary: Flexible Modules for JAX
  license: MIT
  license_file: LICENSE

extra:
  recipe-maintainers:
    - noahjutz
