{% set name = "miranda" %}
{% set version = "0.6.0" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.org/packages/source/{{ name[0] }}/{{ name }}/miranda-{{ version }}.tar.gz
  sha256: 46a10999cb50af134ec70fcf9cae822182105f0fb3b6de8d4eef1ca5277481b9

build:
  noarch: python
  script: {{ PYTHON }} -m pip install . -vv --no-deps --no-build-isolation
  number: 0

requirements:
  host:
    - python >=3.10.0
    - flit-core >=3.11.0,<4
    - pip
  run:
    - python >=3.10.0
    - cftime
    - cf-xarray >=0.10.4
    - dask-core >=2024.8.1
    - distributed
    - h5netcdf
    - netcdf4 >=1.6.4
    - numcodecs <0.16
    - numpy >=1.25
    - pandas >=1.0.0
    - pyessv
    - pyyaml
    - schema
    - xarray >=2023.11.0
    - xclim >=0.57.0
    - zarr
run_constrained:
    - cdsapi
    - ecmwf-api-client
    - intake
    - intake-esm
    - pyproj
    - regionmask >=0.13.0
    - requests >=2.31.0
    - s3fs
    - shapely >=2.0.0
    - xesmf

test:
  imports:
    - miranda
  commands:
    - pip check
  requires:
    - pip

about:
  home: https://github.com/Ouranosinc/miranda/
  summary: Python utilities for climate data collection, conversion, and management.
  description: |
    Miranda is a Python package that provides utilities for climate data collection,
    conversion, and management. It simplifies the process of handling climate datasets
    by offering tools for downloading, converting formats, and organizing data.
  dev_url: https://github.com/Ouranosinc/miranda/
  doc_url: https://miranda.readthedocs.io/
  license: Apache-2.0
  license_family: Apache
  license_file: LICENSE

extra:
  recipe-maintainers:
    - Zeitsperre
    - tlogan2000
    - aslibese
