{% set version = '0.3.2' %}
{% set posix = 'm2-' if win else '' %}

package:
  name: r-jinjar
  version: {{ version|replace("-", "_") }}

source:
  url:
    - {{ cran_mirror }}/src/contrib/jinjar_{{ version }}.tar.gz
    - {{ cran_mirror }}/src/contrib/Archive/jinjar/jinjar_{{ version }}.tar.gz
  sha256: 0078e8fcb255d7740c997843d661dfd1c8e9fc96d4ff3c742e5718ba3b1ea61e

build:
  number: 0
  rpaths:
    - lib/R/lib/
    - lib/
  missing_dso_whitelist:
    - '*/R.dll'        # [win]
    - '*/Rblas.dll'    # [win]
    - '*/Rlapack.dll'  # [win]

requirements:
  build:
    - {{ compiler('c') }}              # [not win]
    - {{ compiler('m2w64_c') }}        # [win]
    - {{ compiler('cxx') }}            # [not win]
    - {{ compiler('m2w64_cxx') }}      # [win]
    - {{ stdlib("c") }}
    - {{ posix }}filesystem        # [win]
    - {{ posix }}make
    - {{ posix }}sed               # [win]
    - {{ posix }}coreutils         # [win]
    - {{ posix }}zip               # [win]
    - cross-r-base {{ r_base }}    # [build_platform != target_platform]
  host:
    - r-base
    - r-cli
    - r-cpp11
    - r-fs
    - r-jsonlite
    - r-rlang >=1.0.0
  run:
    - r-base
    - r-cli
    - r-cpp11
    - r-fs
    - r-jsonlite
    - r-rlang >=1.0.0

test:
  commands:
    - $R -e "library('jinjar')"           # [not win]
    - "\"%R%\" -e \"library('jinjar')\""  # [win]

about:
  home: https://davidchall.github.io/jinjar/, https://github.com/davidchall/jinjar
  license: MIT
  summary: Template engine powered by the 'inja' C++ library. Users write a template document,
    using syntax inspired by the 'Jinja' Python package, and then render the final document
    by passing data from R. The template syntax supports features such as variables,
    loops, conditions and inheritance.
  license_family: MIT
  license_file:
    - '{{ environ["PREFIX"] }}/lib/R/share/licenses/MIT'
    - LICENSE

extra:
  recipe-maintainers:
    - conda-forge/r
    - snowpong



# Package: jinjar
# Title: Template Engine Inspired by 'Jinja'
# Version: 0.3.2
# Authors@R: c( person("David", "Hall", , "david.hall.physics@gmail.com", role = c("aut", "cre", "cph"), comment = c(ORCID = "0000-0002-2193-0480")), person("Lars", "Berscheid", role = "cph", comment = "Author of bundled inja library"), person("Niels", "Lohmann", role = "cph", comment = "Author of bundled json library") )
# Description: Template engine powered by the 'inja' C++ library. Users write a template document, using syntax inspired by the 'Jinja' Python package, and then render the final document by passing data from R. The template syntax supports features such as variables, loops, conditions and inheritance.
# License: MIT + file LICENSE
# URL: https://davidchall.github.io/jinjar/, https://github.com/davidchall/jinjar
# BugReports: https://github.com/davidchall/jinjar/issues
# Imports: cli, fs, jsonlite, rlang (>= 1.0.0)
# Suggests: knitr, rmarkdown, testthat
# LinkingTo: cpp11
# VignetteBuilder: knitr
# Config/testthat/edition: 3
# Encoding: UTF-8
# Language: en-US
# RoxygenNote: 7.3.2
# NeedsCompilation: yes
# Packaged: 2025-03-13 02:29:35 UTC; davidhall
# Author: David Hall [aut, cre, cph] (<https://orcid.org/0000-0002-2193-0480>), Lars Berscheid [cph] (Author of bundled inja library), Niels Lohmann [cph] (Author of bundled json library)
# Maintainer: David Hall <david.hall.physics@gmail.com>
# Repository: CRAN
# Date/Publication: 2025-03-13 03:40:02 UTC
