{% set name = "chumpy" %}
{% set version = "0.70" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.org/packages/source/{{ name[0] }}/{{ name }}/{{ name }}-{{ version }}.tar.gz
  sha256: a0275c2018784ca1302875567dc81761f5fd469fab9f3ac0f3e7c39e9180350a

build:
  noarch: python
  script: {{ PYTHON }} -m pip install . -vv --no-deps --no-build-isolation
  number: 0

requirements:
  host:
    - pip
    - python {{ python_min }}
    - setuptools
  run:
    - python >={{ python_min }}
    - numpy >=1.8.1
    - scipy >=0.13.0
    - six >=1.11.0

test:
  imports:
    - chumpy
  commands:
    - pip check
  requires:
    - pip
    - python {{ python_min }}

about:
  home: https://github.com/mattloper/chumpy
  summary: 'chumpy is a Python-based framework designed to handle the auto-differentiation problem'
  description: |
    chumpy is a Python-based framework designed to handle the auto-differentiation
    problem. It is intended to be fast, flexible, and easy to use. It was originally
    developed as part of the SMPL human body model project, but has since been
    extracted into a separate package.
  license: MIT
  license_file: LICENSE.txt
  dev_url: https://github.com/mattloper/chumpy

extra:
  recipe-maintainers:
    - jeongseok-meta
