# This would ideally use CFEP-25 `python_min`, but `staged-recipes` doesn't
# yet build python 3.14 by default.
is_noop:
  - "false"
  - "true"
# python_min:
#  - "3.10"  # this would need to be updated yearly
#  - "3.14"
