{% set name = "backports.zstd" %}
{% set version = "0.5.0" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.org/packages/source/{{ name[0] }}/{{ name }}/backports_zstd-{{ version }}.tar.gz
  sha256: 7130d6bded652a3139fafba875283a74380a4f308f24d2361ea8761e49f837e9

build:
  skip: true  # [py>=314]
  noarch: python
  script: {{ PYTHON }} -m pip install . -vv --no-deps --no-build-isolation
  number: 0

requirements:
  build:
    - {{ compiler('c') }}
  host:
    - pip
    - python >=3.9,<3.14
    - setuptools
  run:
    - python >=3.9,<3.14

test:
  imports:
    - backports
    - backports.zstd
  requires:
    - pip
  commands:
    - pip check

about:
  summary: Backport of compression.zstd
  home: https://github.com/rogdham/backports.zstd
  license: BSD-3-Clause AND MIT AND EPL-2.0
  license_file:
    - LICENSE.txt
    - src/c/pythoncapi-compat/COPYING
    - src/c/zstd/LICENSE

extra:
  recipe-maintainers:
    - rogdham
