{% set name = "backports.zstd" %}
{% set version = "1.0.0" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.org/packages/source/{{ name[0] }}/{{ name }}/backports_zstd-{{ version }}.tar.gz
  sha256: 8e99702fd4092c26624b914bcd140d03911a16445ba6a74435b29a190469cce3

build:
  skip: true  # [py<39 or py>=314]
  script: {{ PYTHON }} -m pip install . -vv --no-deps --no-build-isolation --config-settings=--build-option=--system-zstd
  number: 0

requirements:
  build:
    - {{ compiler('c') }}
    - {{ stdlib('c') }}
  host:
    - pip
    - python
    - setuptools
    - zstd
  run:
    - python

test:
  imports:
    - backports
    - backports.zstd
  requires:
    - pip
  commands:
    - pip check

about:
  summary: Backport of compression.zstd
  home: https://github.com/rogdham/backports.zstd
  license: BSD-3-Clause AND MIT AND EPL-2.0
  license_file:
    - LICENSE.txt

extra:
  recipe-maintainers:
    - rogdham
