# yaml-language-server: $schema=https://raw.githubusercontent.com/prefix-dev/recipe-format/main/schema.json
schema_version: 1

context:
  version: 1.0.0

recipe:
  name: backports.zstd-split
  version: ${{ version }}

source:
  url: https://pypi.org/packages/source/b/backports.zstd/backports_zstd-${{ version }}.tar.gz
  sha256: 8e99702fd4092c26624b914bcd140d03911a16445ba6a74435b29a190469cce3

build:
  number: 0

outputs:
  - package:
      name: backports.zstd
    build:
      skip: is_noop == "true" or match(python, ">=3.14")
      script:
        - ${{ PYTHON }} -m pip install . -vv --no-deps --no-build-isolation --config-settings=--build-option=--system-zstd --disable-pip-version-check
    requirements:
      build:
        - ${{ compiler("c") }}
        - ${{ stdlib("c") }}
      host:
        - pip
        - python
        - setuptools
        - zstd
      run:
        - python
    tests:
      - python:
          imports: backports.zstd
          pip_check: true

  - package:
      name: backports.zstd
    build:
      skip: is_noarch == "true"
      noarch: python
    requirements:
      host:
        - python >=3.14
      run:
        - python >=3.14
    tests:
      - python:
          imports: compression.zstd
          pip_check: true
    about:
      homepage: https://github.com/rogdham/backports.zstd
      license: BSD-3-Clause AND MIT AND EPL-2.0
      license_file: LICENSE.txt
      summary: Backport of compression.zstd (no-op on Python 3.14+)

about:
  homepage: https://github.com/rogdham/backports.zstd
  license: BSD-3-Clause AND MIT AND EPL-2.0
  license_file: LICENSE.txt
  summary: Backport of compression.zstd

extra:
  recipe-maintainers:
    - rogdham
    - bollwyvl
