{% set python_min = "3.10" %}
{% set name = "blop" %}
{% set version = "0.8.0" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.org/packages/source/{{ name[0] }}/{{ name }}/blop-{{ version }}.tar.gz
  sha256: 7b6d16fe897ae5f469fecce0ce9318df9635dd0b9c78665259a08b8b65af8d42

build:
  noarch: python
  script: {{ PYTHON }} -m pip install . -vv --no-deps --no-build-isolation
  number: 0

requirements:
  host:
    - python {{ python_min }}
    - hatch-vcs
    - hatchling
    - pip
  run:
    - python >={{ python_min }}
    - python-tsp
    - ax-platform >=1.0.0,<1.1
    - bluesky-base >=1.14.4,<2
    - databroker >=1.2.0,<1.3
    - tiled >=0.1.1
    - pytorch
    - matplotlib-base
    - pyqt >=5.15.11,<6
    - ophyd
    - botorch >=0.14.0,<0.15
    - gpytorch >=1.14,<2
    - scipy
    - numpy
    - h5py
    - area-detector-handlers
    - bluesky-tiled-plugins
    - networkx ~=2.1
    - tabulate ~=0.8.7

test:
  imports:
    # The list of imports is generated via the following command:
    #   $ cd <blop-repo>/src
    #   $ find blop -name "*.py" | grep -v tests | sed 's/.__init__.py//g' | sed 's/._version//g' | sed 's;/;.;g' | sed 's/\.py//g'| sort -u
    - blop
    - blop.ax
    - blop.ax.agent
    - blop.agent
    - blop.bayesian
    - blop.bayesian.acquisition
    - blop.bayesian.acquisition.analytic
    - blop.bayesian.acquisition.monte_carlo
    - blop.bayesian.kernels
    - blop.bayesian.models
    - blop.de
    - blop.de.de_opt_utils
    - blop.de.de_optimization
    - blop.de.hardware_flyer
    - blop.digestion
    - blop.digestion_function
    - blop.dofs
    - blop.objectives
    - blop.plans
    - blop.plotting
    - blop.utils
    - blop.utils.functions
    - blop.utils.sets
  commands:
    - pip check
  requires:
    - python {{ python_min }}
    - pip
    - area-detector-handlers
    - databroker =1.2.5

about:
  home: https://github.com/NSLS-II/blop
  summary: Beamline optimization with machine learning
  license: BSD-3-Clause
  license_family: BSD
  license_file: LICENSE
  doc_url: https://nsls-ii.github.io/blop

extra:
  recipe-maintainers:
    - mrakitin
    - thomaswmorris
    - thopkins32
