{% set name = "huxt" %}
{% set version = "5.0.0" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  
  url: https://github.com/University-of-Reading-Space-Science/HUXt/releases/download/{{ version }}/huxt-{{ version }}.tar.gz
  sha256: 2b3a0c466fb4a1014ea131c2b8ea7c519f9278eba73d6fcb361b7bdb4fd494e9
  # sha256 is the preferred checksum -- you can get it for a file with:
  #  `openssl sha256 <file name>`.
  # You may need the openssl package, available on conda-forge:
  #  `conda install openssl -c conda-forge``

build:
  noarch: python
  script: {{ PYTHON }} -m pip install . -vv
  number: 0
   entry_points:
    - huxt-make-ephemeris = huxt.scripts.make_ephemeris:main
    - huxt-open-examples = huxt.scripts.open_examples_notebook:main

requirements:
  host:
    - python ==3.12.11
    - appdirs ==1.4.4
    - astropy ==7.1.0
    - dtaidistance ==2.3.13
    - h5py ==3.14.0
    - httplib2 ==0.30.0
    - imageio ==2.37.0
    - imageio-ffmpeg ==0.6.0
    - jupyterlab ==4.4.7
    - matplotlib ==3.10.6
    - numba ==0.61.2
    - numpy ==2.2.6
    - pandas ==2.3.2
    - pyhdf ==0.11.6
    - requests ==2.32.5
    - scipy ==1.16.1
    - sunpy ==7.0.1
  run:
    - python ==3.12.11
    - appdirs ==1.4.4
    - astropy ==7.1.0
    - dtaidistance ==2.3.13
    - h5py ==3.14.0
    - httplib2 ==0.30.0
    - imageio ==2.37.0
    - imageio-ffmpeg ==0.6.0
    - jupyterlab ==4.4.7
    - matplotlib ==3.10.6
    - numba ==0.61.2
    - numpy ==2.2.6
    - pandas ==2.3.2
    - pyhdf ==0.11.6
    - requests ==2.32.5
    - scipy ==1.16.1
    - sunpy ==7.0.1

test:
  requires:
    - pytest
   source_files:
    - tests/
  commands:
    - pytest tests

about:
  home: https://github.com/University-of-Reading-Space-Science/HUXt
  summary: 'A computationally efficient solar wind model'
  description: |
    HUXt is a python implelementation of a computationally efficient solar wind model.
  license: MIT
  license_family: MIT
  license_file: LICENSE.txt
  
extra:
  recipe-maintainers:
    - LukeBarnard
