{% set name = "ticoi" %}
{% set version = "0.0.1" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.org/packages/source/{{ name[0] }}/{{ name }}/ticoi-{{ version }}.tar.gz
  sha256: 5e35b32b22873452c66f58f72045a532367f3462688bbe8438a8eb66e0a19ee2

build:
  noarch: python
  script: {{ PYTHON }} -m pip install . -vv --no-deps --no-build-isolation
  number: 0

requirements:
  host:
    - python >=3.10
    - hatchling
    - pip
  run:
    - python >=3.10
    - aiohttp
    - dask-core
    - geopandas
    - jdcal
    - joblib
    - h5netcdf
    - matplotlib-base
    - notebook
    - numba
    - numpy
    - pandas
    - pyproj
    - rasterio
    - requests
    - rioxarray
    - scipy
    - scikit-learn
    - seaborn
    - shapely
    - statsmodels
    - tqdm
    - xarray
    - zarr

test:
  imports:
    - ticoi
  commands:
    - pip check
  requires:
    - pip

about:
  home: https://pypi.org/project/ticoi/
  summary: A package to run Temporal Inversion using linear Combinations of Observations, and Interpolation (TICOI)
  dev_url: https://github.com/ticoi/ticoi
  license: LGPL-3.0-only
  license_file: LICENSE

extra:
  recipe-maintainers:
    - LauraneC
    - Leiguo924
    - adehecq
