{% set name = "pleiades-neutron" %}
{% set version = "2.1.1" %}
{% set python_min = "3.10" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.org/packages/source/{{ name[0] }}/{{ name }}/pleiades_neutron-{{ version }}.tar.gz
  sha256: 78cdad6834a24a301d571ab5d2b0b81482f177c15ab37d85b775eeeedc03c0a9

build:
  entry_points:
    - pleiades = pleiades:main
    - post_install_check = pleiades.post_install:check_sammy_installed
  noarch: python
  script: {{ PYTHON }} -m pip install . -vv --no-deps --no-build-isolation
  number: 0

requirements:
  host:
    - python {{ python_min }}
    - setuptools >=40.6.0
    - wheel
    - toml
    - versioningit
    - pip
  run:
    - python >={{ python_min }}
    - numpy
    - scipy
    - pandas
    - astropy-base
    - matplotlib-base
    - tifffile
    - jupyterlab
    - dxchange
    - pyyaml
    - scikit-image
    - pydantic
    - loguru
    - nova-galaxy >=0.7.4,<0.8

test:
  imports:
    - pleiades
  commands:
    - pip check
    - pleiades --help
    - post_install_check --help
  requires:
    - pip
    - python {{ python_min }}

about:
  home: https://github.com/lanl/PLEIADES
  summary: PLEIADES - Python Libraries Extensions for Isotopic Analysis via Detailed Examination of SAMMY
  license: MIT
  license_file: LICENSE

extra:
  recipe-maintainers:
    - KedoKudo
