{% set version = '0.1.8' %}

{% set posix = 'm2-' if win else '' %}
{% set native = 'm2w64-' if win else '' %}

package:
  name: r-thematic
  version: {{ version|replace("-", "_") }}

source:
  url:
    - {{ cran_mirror }}/src/contrib/thematic_{{ version }}.tar.gz
    - {{ cran_mirror }}/src/contrib/Archive/thematic/thematic_{{ version }}.tar.gz
  sha256: 609a7c5dfa64b9e6796059078b09bdad1377d072174ea3425b3c2e0c18ad4145

build:
  merge_build_host: True  # [win]

  number: 0


  # This is required to make R link correctly on Linux.
  rpaths:
    - lib/R/lib/
    - lib/

# Suggests: bslib, Cairo, curl, gganimate, ggiraph, htmltools, jsonlite, knitr, lattice, ragg, rmarkdown, shiny (>= 1.5.0), showtext, stats, svglite, sysfonts, systemfonts, testthat, vdiffr (>= 1.0.0), withr
requirements:
  build:
    - {{ posix }}zip               # [win]

  host:
    - r-base
    - r-farver
    - r-ggplot2 >=3.5.2
    - r-rappdirs
    - r-rlang
    - r-rstudioapi >=0.8
    - r-scales

  run:
    - r-base
    - r-farver
    - r-ggplot2 >=3.5.2
    - r-rappdirs
    - r-rlang
    - r-rstudioapi >=0.8
    - r-scales

test:
  commands:
    # You can put additional test commands to be run here.
    - $R -e "library('thematic')"           # [not win]
    - "\"%R%\" -e \"library('thematic')\""  # [win]

  # You can also put a file called run_test.r, run_test.py, run_test.sh,
  # or run_test.bat in the recipe that will be run at test time.

  # requires:
    # Put any additional test requirements here.

about:
  home: https://rstudio.github.io/thematic/, https://github.com/rstudio/thematic
  license: MIT
  summary: Theme 'ggplot2', 'lattice', and 'base' graphics based on a few choices, including
    foreground color, background color, accent color, and font family. Fonts that aren't
    available on the system, but are available via download on 'Google Fonts', can be
    automatically downloaded, cached, and registered for use with the 'showtext' and
    'ragg' packages.
  license_family: MIT
  license_file:
    - '{{ environ["PREFIX"] }}/lib/R/share/licenses/MIT'
    - LICENSE

extra:
  recipe-maintainers:
    - snowpong
