{% set name = "vape4d" %}
{% set version = "0.2.5" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.org/packages/source/{{ name[0] }}/{{ name }}/vape4d-{{ version }}.tar.gz
  sha256: 6fbc1af308b317ef0cb59ba380088494ed8f05c3b3f38d079afece8329259ce3

build:
  noarch: python
  script: {{ PYTHON }} -m pip install . -vv --no-deps --no-build-isolation
  number: 0

requirements:
  host:
    - python >=3.8
    - maturin >=1.0,<2.0
    - pip
  run:
    - python >=3.8
    - numpy
    - matplotlib-base
    - seaborn
    - cmasher
    - cffi

test:
  imports:
    - vape4d
  commands:
    - pip check
  requires:
    - pip

about:
  summary: Volume 4D Visualization
  license: ''
  license_file: PLEASE_ADD_LICENSE_FILE

extra:
  recipe-maintainers:
    - sarthakpati
