{% set name = "hybgensea" %}
{% set version = "0.0.1" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.org/packages/source/{{ name[0] }}/{{ name }}/hybgensea-{{ version }}.tar.gz
  sha256: 61438cb87f571d66698739ba9709aa3ab65fa278274c6b70e0b9a1ca3adf1824

build:
  script: {{ PYTHON }} -m pip install . -vv --no-deps --no-build-isolation
  number: 0

requirements:
  build:
    - {{ compiler('cxx') }}
    - {{ stdlib("c") }}
    - cmake
    - make
  host:
    - python
    - scikit-build-core
    - pip
  run:
    - python
    - numpy

test:
  imports:
    - hybgensea
  commands:
    - pip check
  requires:
    - pip

about:
  home: https://github.com/mdealencar/PyHygese
  summary: Wrapper for the Hybrid Genetic Search algorithm for Capacitated Vehicle Routing Problems (HGS-CVRP)
  license: MIT
  license_file: LICENSE

extra:
  recipe-maintainers:
    - mdealencar
