{% set name = "album-distributed" %}
{% set version = "0.2.0" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.org/packages/source/{{ name[0] }}/{{ name }}/album_distributed-{{ version }}.tar.gz
  sha256: 17071322ed0c7b8d59deed8a0b932221abf37c1caa6d453d4f5413b9065f6f0f

build:
  noarch: python
  script: {{ PYTHON }} -m pip install . -vv --no-deps --no-build-isolation
  number: 0

requirements:
  host:
    - python >=3.7
    - pip
  run:
    - python >=3.7
    - album >=0.9.2,<0.13

test:
  imports:
    - album
  commands:
    - pip check
  requires:
    - pip

about:
  home: https://gitlab.com/album-app/plugins/album-run-distributed
  summary: album plugin for running a solution repeatedly and distributed
  dev_url: https://gitlab.com/album-app/plugins/album-distributed
  license: MIT
  license_file: LICENSE

extra:
  recipe-maintainers:
    - jpalbrecht
