schema_version: 1

context:
  name: advanced-alchemy
  version: 1.7.0

package:
  name: ${{ name|lower }}
  version: ${{ version }}

source:
  url: https://pypi.org/packages/source/${{ name[0] }}/${{ name }}/advanced_alchemy-${{ version }}.tar.gz
  sha256: ee15913f066a06a43c376402041f2a013f2d51893d54f52c4612782cd16023ab

build:
  noarch: python
  number: 0
  script: ${{ PYTHON }} -m pip install . -vv --no-deps --no-build-isolation
  python:
    entry_points:
      - alchemy = advanced_alchemy.__main__:run_cli

requirements:
  host:
    - python ${{ python_min }}.*
    - hatchling
    - pip
  run:
    - python >=${{ python_min }}
    - sqlalchemy >=2.0.20
    - alembic >=1.12.0
    - typing_extensions >=4.0.0
    - greenlet
    - eval-type-backport

tests:
  - python:
      imports:
        - advanced_alchemy
      pip_check: true
      python_version: ${{ python_min }}.*
  - requirements:
      run:
        - python ${{ python_min }}.*
    script:
      - alchemy --help

about:
  summary: Ready-to-go SQLAlchemy concoctions.
  license: MIT
  license_file: LICENSE
  homepage: https://github.com/litestar-org/advanced-alchemy

extra:
  recipe-maintainers:
    - thewchan
