{% set name = "hallelujah" %}
{% set version = "0.0.2" %}
{% set python_min = "3.12" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.org/packages/source/{{ name[0] }}/{{ name }}/hallelujah-{{ version }}.tar.gz
  sha256: 7b1c8249d3fd4616ebce7fcc58676ab8bf2ee5e4596abdbb8e28277fbd16ffa8

build:
  entry_points:
    - pray = hallelujah.app:main
    - test_pray = hallelujah.test:main
    - batch_pray = hallelujah.batch:main
  noarch: python
  script: {{ PYTHON }} -m pip install . -vv --no-deps --no-build-isolation
  number: 0

requirements:
  host:
    - python {{ python_min }}
    - pip
    - setuptools
  run:
    - python >={{ python_min }}
    - numpy >=2.2.1
    - scipy >=1.15.0
    - networkx >=3.4.2

test:
  imports:
    - hallelujah
  commands:
    - pip check
    - pray --help
    - test_pray --help
    - batch_pray --help
  requires:
    - pip
    - python {{ python_min }}

about:
  home: https://github.com/frankvegadelgado/hallelujah
  summary: Compute the Approximate Vertex Cover for undirected graph encoded in DIMACS format.
  license: MIT
  license_file: LICENSE

extra:
  recipe-maintainers:
    - frankvegadelgado
