{% set name = "hvala" %}
{% set version = "0.0.5" %}
{% set python_min = "3.12" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.org/packages/source/{{ name[0] }}/{{ name }}/hvala-{{ version }}.tar.gz
  sha256: 5ef3a679a0e6ce89ed4f2f24de4657074ff1ea3c111ee2313480b492c6db5d0f

build:
  entry_points:
    - idemo = hvala.app:main
    - test_idemo = hvala.test:main
    - batch_idemo = hvala.batch:main
  noarch: python
  script: {{ PYTHON }} -m pip install . -vv --no-deps --no-build-isolation
  number: 0

requirements:
  host:
    - python {{ python_min }}
    - pip
    - setuptools
  run:
    - python >={{ python_min }}
    - numpy >=2.2.1
    - scipy >=1.15.0
    - networkx >=3.4.2

test:
  imports:
    - hvala
  commands:
    - pip check
    - idemo --help
    - test_idemo --help
    - batch_idemo --help
  requires:
    - pip
    - python {{ python_min }}

about:
  home: https://github.com/frankvegadelgado/hvala
  summary: Compute the Approximate Vertex Cover for undirected graph encoded in DIMACS format.
  license: MIT
  license_file: LICENSE

extra:
  recipe-maintainers:
    - frankvegadelgado
