{% set version = "0.1" %}

package:
  name: othpc
  version: {{ version }}

source:
  url: https://github.com/openturns/othpc/archive/refs/tags/v{{ version }}.tar.gz
  sha256: 4a08f7e2cb9a5f6bf81cdc5cdb4be302a0d74eef8b5694ab5a07105b30daaf41

build:
  noarch: python
  script:
    - {{ PYTHON }} -m pip install . -vv --no-deps --no-build-isolation
    - rm ${SP_DIR}/othpc/example/cantilever_beam/template/{beam,beam_old}
  number: 0

requirements:
  host:
    - python {{ python_min }}
    - pip
    - setuptools
  run:
    - python >={{ python_min }}
    - openturns
    - pandas
    - tqdm
    - submitit
    - packaging

test:
  requires:
    - python {{ python_min }}
    - pip
  commands:
    - pip check
  imports:
    - othpc

about:
  home: https://github.com/openturns/othpc
  summary: 'Evaluate simulation models on HPC clusters'
  description: |
    othpc is a simple Python tool that facilitates the evaluation
    of numerical models on a SLURM based High-Performance Computing (HPC) facility.
  license: LGPL-3.0-or-later
  license_family: LGPL
  license_file: COPYING.LESSER

extra:
  recipe-maintainers:
    - jschueller
