context:
  name: langchain-deepseek
  version: 1.0.0
  python_min: "3.10"

package:
  name: ${{ name|lower }}
  version: ${{ version }}

source:
  url: https://pypi.org/packages/source/${{ name[0] }}/${{ name }}/langchain_deepseek-${{ version }}.tar.gz
  sha256: 8d09bbf42240a918589981e46e5168358aecdf30cc2fbcf6d1888c2bbe0fb62a

build:
  number: 0
  noarch: python
  script: ${{ PYTHON }} -m pip install . -vv --no-deps --no-build-isolation

requirements:
  host:
    - python ${{ python_min }}.*
    - hatchling
    - pip
  run:
    - python >=${{ python_min }} 
    - langchain-core >=1.0.0,<2.0.0
    - langchain-openai >=1.0.0,<2.0.0

tests:
  - python:
      imports:
        - langchain_deepseek
      pip_check: true
      python_version: ${{ python_min }}.*

about:
  summary: An integration package connecting DeepSeek and LangChain
  license: MIT
  license_file: LICENSE
  repository: https://github.com/langchain-ai/langchain/blob/master/libs/partners/deepseek
  homepage: https://reference.langchain.com/python/integrations/langchain_deepseek/

extra:
  recipe-maintainers:
    - MridulS
