How to do it: package:
  name: pychop
  version: 0.3.6

source:
  url: https://pypi.org/packages/source/p/pychop/pychop-0.3.6.tar.gz
  sha256: e828be685e31c679c7ae5f2f0dee350f466b065d37d27b9dd516716a45e14e3a

build:
  number: 0
  script:
    - {{ PYTHON }} -m pip install . -vv
  noarch: python
  skip: True  # [win]

requirements:
  host:
    - python
    - pip
    - setuptools
    - numpy >=1.17.2
  run:
    - python >=3.7  # fix
    - numpy >=1.17.2
    - pandas
    - dask
    - pytorch >=1.12
    - jax >=0.4.8 # [not win] 

test:
  requires:
    - scipy
    - pytorch >=1.12
    - jax >=0.4.8  
    - pytest
    - pip
  imports:
    - pychop
    - pychop.np
    - pychop.tch
    - pychop.jx # [not win]
  commands:
    - pip check  

about:
  home: https://github.com/inexascale/pychop
  license: MIT
  license_file: LICENSE
  summary: Python library for simulating low precision floating-point arithmetic
  description: |
    Pychop is a Python library designed to facilitate numerical experimentation with low-precision arithmetic. 
    It supports customizable floating-point formats and a comprehensive set of rounding modes, 
    integrating seamlessly with NumPy, PyTorch, and JAX for efficient low-precision emulation 
    in deep learning and scientific computations.
  doc_url: https://pychop.readthedocs.io/en/latest/?badge=latest
  dev_url: https://github.com/inexascale/pychop
  license_family: MIT

extra:
  recipe-maintainers:
    - eccarson
    - chenxinye
