# yaml-language-server: $schema=https://raw.githubusercontent.com/prefix-dev/recipe-format/main/schema.json
schema_version: 1

context:
  version: 0.4.0

package:
  name: pluck-graphql
  version: ${{ version }}

source:
  url: https://pypi.org/packages/source/p/pluck-graphql/pluck_graphql-${{ version }}.tar.gz
  sha256: 7f143fe2f640c525f8496db448cf4a91dafa283da93dc0ddf8e6afd11c26a34e

build:
  number: 0
  noarch: python
  script:
    - ${{ PYTHON }} -m pip install . -vv --no-deps --no-build-isolation --disable-pip-version-check

requirements:
  host:
    - python ${{ python_min }}.*
    - poetry-core
    - pip
  run:
    - python >=${{ python_min }}
    - pandas >=1.4
    - graphql-core >=3.2.1,<4.0.0

tests:
  - python:
      imports: pluck
      pip_check: true
      python_version:
        - ${{ python_min }}.*
        - 3.14.*

about:
  summary: Transform GraphQL queries into Pandas data-frames.
  license: MIT
  license_file: LICENSE
  homepage: https://github.com/galpin/pluck

extra:
  recipe-maintainers:
    - bollwyvl
