context:
  name: "granular"
  version: "0.21.0"

package:
  name: ${{ name|lower }}
  version: ${{ version }}

source:
  url: https://pypi.org/packages/source/${{ name[0] }}/${{ name }}/${{ name }}-${{ version }}.tar.gz
  sha256: 7139ba3f153c05e9066f7f67acb0d0acec7120137e89ca891499b726b29e6a17

build:
  script: ${{ PYTHON }} -m pip install . -vv --no-deps --no-build-isolation
  number: 0

requirements:
  host:
    - python ${{ python_min }}.*
    - setuptools
    - pip
  run:
    - python >=${{ python_min }}
    - cloudpickle
    - msgpack-python
    - numpy

tests:
  - python:
      imports:
        - granular
      python_version: ${{ python_min }}.*


about:
  homepage: http://github.com/danijar/granular
  summary: Fast format for datasets.
  license: MIT
  license_file: LICENSE

extra:
  recipe-maintainers:
    - noahjutz
