{% set name = "torchfsm" %}
{% set version = "0.0.1" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://github.com/qiauil/torchfsm/releases/download/v{{ version }}/torchfsm-{{ version }}.tar.gz
  sha256: 90965f06bb9f79a122b28af710610f836efdb26a44147584b1da997a4093b56f
  patch:
    - patch.diff

build:
  noarch: python
  script: {{ PYTHON }} -m pip install . -vv --no-deps --no-build-isolation
  number: 0

requirements:
  host:
    - python {{ python_min }}
    - pip
    - setuptools
  run:
    - python >={{ python_min }}
    - ipython
    - matplotlib-base
    - numpy
    - pytorch
    - tqdm
    - vape4d

test:
  imports:
    - torchfsm
  # commands:
  #   - pip check
  requires:
    - python {{ python_min }}
    - pip

about:
  home: https://qiauil.github.io/torchfsm
  summary: Fourier Spectral Method with PyTorch
  license: MIT
  license_file: LICENSE

extra:
  recipe-maintainers:
    - sarthakpati
