{% set name = "grapes" %}
{% set version = "0.10.4" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.org/packages/source/{{ name[0] }}/{{ name }}/grapes-{{ version }}.tar.gz
  sha256: 2c71678e7d7eb98e31483202dac838e5567c2f8d77183339caa90b8966a13aff

build:
  script: {{ PYTHON }} -m pip install . -vv --no-deps --no-build-isolation
  noarch: python
  number: 0

requirements:
  host:
    - python {{ python_min }}
    - hatchling
    - pip
  run:
    - python >={{ python_min }}
    - matplotlib-base
    - networkx
    - tomli
    - pygraphviz

test:
  imports:
    - grapes
  commands:
    - pip check
  requires:
    - python {{ python_min }}
    - pip

about:
  home: https://github.com/giuliofoletto/grapes
  summary: Helper for dataflow based programming
  license: Apache-2.0
  license_file:
    - LICENSE.txt
    - NOTICE.txt

extra:
  recipe-maintainers:
    - giuliofoletto
