# yaml-language-server: $schema=https://raw.githubusercontent.com/prefix-dev/recipe-format/main/schema.json
schema_version: 1

context:
  version: "0.3.0"

package:
  name: wiredb
  version: ${{ version }}

source:
  - url: https://pypi.org/packages/source/w/wiredb/wiredb-${{ version }}.tar.gz
    sha256: 8eb6be8460da16e2662a45ef76206778fdf4731db112eeca224e48cdfef0fbab

build:
  number: 0
  noarch: python
  script:
    - ${{ PYTHON }} -m pip install . -vv --no-deps --no-build-isolation --disable-pip-version-check

requirements:
  host:
    - pip
    - python ${{ python_min }}.*
    - uv-build
  run:
    - python >=${{ python_min }}
    - anyio >=4.11.0,<5.0.0
    - pycrdt >=0.12.41,<0.13.0
    - typing_extensions >=4.15.0,<5.0.0

tests:
  - python:
      imports: wiredb
      pip_check: true
      python_version: ${{ python_min }}.*

about:
  license: MIT
  license_file: LICENSE
  homepage: https://github.com/davidbrochart/wiredb
  summary: Distributed database built on top of CRDTs.

extra:
  recipe-maintainers:
    - davidbrochart
