{% set name = "tlv8" %}
{% set version = "0.10.0" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.org/packages/source/{{ name[0] }}/{{ name }}/tlv8-{{ version }}.tar.gz
  sha256: 7930a590267b809952272ac2a27ee81b99ec5191fa2eba08050e0daee4262684

build:
  noarch: python
  script: {{ PYTHON }} -m pip install . -vv --no-deps --no-build-isolation
  number: 0

requirements:
  host:
    - python {{ python_min }}
    - pip
    - setuptools
  run:
    - python >={{ python_min }}

test:
  imports:
    - tlv8
  commands:
    - pip check
  requires:
    - python {{ python_min }}
    - pip

about:
  home: https://github.com/jlusiardi/tlv8_python
  summary: Python module to handle type-length-value (TLV) encoded data 8-bit type, 8-bit length, and N-byte value as described within the Apple HomeKit Accessory Protocol Specification Non-Commercial Version Release R2.
  license: Apache-2.0
  license_file: LICENSE

extra:
  recipe-maintainers:
    - FelixMoelder
