{% set name = "pyiron-workflow-atomistics" %}
{% set version = "0.0.2" %}
{% set python_min = "3.11" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.org/packages/source/{{ name[0] }}/{{ name }}/pyiron_workflow_atomistics-{{ version }}.tar.gz
  sha256: 9d87dc036a5edb7273f593422d2d763ca9b6f6cfc36996299dce6042c2f5b0c5

build:
  noarch: python
  script: {{ PYTHON }} -m pip install . -vv --no-deps --no-build-isolation
  number: 0

requirements:
  host:
    - python {{ python_min }}
    - setuptools
    - versioneer ==0.29
    - pip
  run:
    - python >={{ python_min }}
    - numpy >=1.22.0,<1.27.0
    - pandas >=1.3.0,<2.4.0
    - matplotlib-base >=3.10.6,<3.11.0
    - ase >=3.21.0,<3.27.0
    - scipy >=1.4.0,<1.17.0
    - pyiron_workflow >=0.14.1,<=0.15.2
    - pymatgen >=2024.8.8,<2025.7.0
    - pyiron_snippets >=0.1.0,<=0.2.0
    - scikit-learn >=1.0.0,<1.8.0

test:
  imports:
    - pyiron_workflow_atomistics
  commands:
    - pip check
  requires:
    - pip
    - python {{ python_min }}
    
about:
  home: https://github.com/pyiron/pyiron_workflow_atomistics
  summary: A pyiron-workflow module for atomistic simulation workflows
  license: BSD-3-Clause
  license_file: LICENSE

extra:
  recipe-maintainers:
    - ligerzero-ai
