{% set version = "4.4.2" %}
{% set python_min = "3.10" %}

package:
  name: pylabfea
  version: {{ version }}

source:
  url: https://pypi.org/packages/source/p/pylabfea/pylabfea-{{ version }}.tar.gz
  sha256: 73a1368c1d1ccfc24eff02d16f714eda0b9f31045a7fa3aaf997ac703b5a6e70

build:
  noarch: python
  number: 0
  script: {{ PYTHON }} -m pip install . -vv --no-deps --no-build-isolation

requirements:
  host:
    - python {{ python_min }}
    - pip
    - setuptools
  run:
    - python >={{ python_min }}
    - numpy
    - matplotlib-base
    - scipy
    - scikit-learn
    - ipympl

test:
  requires:
    - python {{ python_min }}
    - pip
  imports:
    - pylabfea
  commands:
    - pip check


about:
  home: https://ahartmaier.github.io/pyLabFEA/
  license: GPL-3.0-or-later
  license_file: LICENSE
  summary: "Python Laboratory for Finite Element Analysis"
  description: |
    pyLabFEA is a lightweight Python library for finite element analysis.
    It provides educational and research tools for intuitive FEA modeling with machine learning constitutive models.
  dev_url: https://github.com/AHartmaier/pyLabFEA

extra:
  recipe-maintainers:
    - AHartmaier
