package:
  name: pylabfea
  version: "4.3.7"

source:
  git_url: https://github.com/AHartmaier/pyLabFEA.git
  git_rev: main

build:
  noarch: python
  script: python -m pip install .
  
requirements:
  host:
    - python >=3.8
    - pip
  run:
    - python >=3.8
    - numpy
    - matplotlib
    - scipy
    - scikit-learn
    - pytest
    - jupyter
    - jupyterlab
    - ipympl

test:
  imports:
    - pylabfea

about:
  home: https://github.com/AHartmaier/pyLabFEA
  license: GPLv3
  license_file: LICENSE
  summary: "Finite element analysis toolkit in Python"
  description: |
    pyLabFEA is a lightweight Python library for finite element analysis.
    It aims to provide educational and research tools for small-scale FEA modeling.
  dev_url: https://github.com/AHartmaier/pyLabFEA

extra:
  recipe-maintainers:
    - AHartmaier