{% set name = "pylabfea" %}
{% set version = "4.3.7" %}
{% set python_min = "3.10" %}

package:
  name: {{ name }}
  version: {{ version }}

source:
  git_url: https://github.com/AHartmaier/pyLabFEA.git
  git_rev: v4.4.1

build:
  noarch: python
  number: 0
  script: pip install . -vv

requirements:
  host:
    - python {{ python_min }}
    - pip
    - setuptools
  run:
    - python >={{ python_min }}
    - numpy
    - matplotlib
    - scipy
    - scikit-learn
    - ipympl

test:
  imports:
    - pylabfea
  requires:
    - python {{ python_min }}

about:
  home: https://github.com/AHartmaier/pyLabFEA
  license: GPL-3.0-or-later
  license_file: LICENSE
  summary: "Finite element analysis toolkit in Python"
  description: |
    pyLabFEA is a lightweight Python library for finite element analysis.
    It aims to provide educational and research tools for small-scale FEA modeling 
    with machine learning constitutive models.
  dev_url: https://github.com/AHartmaier/pyLabFEA

extra:
  recipe-maintainers:
    - AHartmaier
