{% set name = "pylabfea" %}
{% set version = "4.3.7" %}
{% set python_min = "3.8" %}

package:
  name: {{ name }}
  version: {{ version }}

source:
  git_url: https://github.com/AHartmaier/pyLabFEA.git
  git_rev: main

build:
  noarch: python
  number: 0
  script: pip install . --no-deps -vv


  
requirements:
  host:
    - python >=3.8
    - pip
    - setuptools
  run:
    - python >=3.8
    - numpy
    - matplotlib-base
    - scipy
    - scikit-learn
    - pytest
    - jupyter
    - jupyterlab
    - ipympl

test:
  imports:
    - pylabfea
  requires:
    - python {{ python_min }}

about:
  home: https://github.com/AHartmaier/pyLabFEA
  license: GPL-2.0-or-later
  license_file: LICENSE
  summary: "Finite element analysis toolkit in Python"
  description: |
    pyLabFEA is a lightweight Python library for finite element analysis.
    It aims to provide educational and research tools for small-scale FEA modeling.
  dev_url: https://github.com/AHartmaier/pyLabFEA

extra:
  recipe-maintainers:
    - AHartmaier
