{% set name = "pylabfea" %}
{% set version = "4.4.1" %}
{% set python_min = "3.10" %}

package:
  name: {{ name }}
  version: {{ version }}

source:
  url: https://github.com/AHartmaier/pyLabFEA/archive/refs/tags/v4.4.1.tar.gz
  sha256: a82b6fed140a987c6b2558428b75b218d67d46cec7fbc06e611bdd21a79b44dc

build:
  noarch: python
  number: 0
  script: {{ PYTHON }} -m pip install . -vv --no-deps --no-build-isolation

requirements:
  host:
    - python {{ python_min }}
    - pip
    - setuptools
  run:
    - python >={{ python_min }}
    - numpy
    - matplotlib-base
    - scipy
    - scikit-learn
    - ipympl

test:
  imports:
    - pylabfea
  commands:
    - pip check
  requires:
    - pip
    - python {{ python_min }}

about:
  home: https://github.com/AHartmaier/pyLabFEA
  license: GPL-3.0-or-later
  license_file: LICENSE
  summary: "Finite element analysis toolkit in Python"
  description: |
    pyLabFEA is a lightweight Python library for finite element analysis.
    It aims to provide educational and research tools for small-scale FEA modeling 
    with machine learning constitutive models.
  dev_url: https://github.com/AHartmaier/pyLabFEA

extra:
  recipe-maintainers:
    - AHartmaier
