context:
  name: msgraphfs
  version: "0.3"

package:
  name: ${{ name|lower }}
  version: ${{ version }}

source:
  url: https://pypi.org/packages/source/${{ name[0] }}/${{ name }}/${{ name }}-${{ version }}.tar.gz
  sha256: c426bd9d954c3ad03fd8ac686091eaa9b29a16db2c0c9e6f222795c14781c4f6

build:
  script: python -m pip install . -vv
  number: 0
  noarch: python

requirements:
  host:
    - python ${{ python_min }}.*
    - pip
    - hatchling
    - hatch-vcs
  run:
    - python >=${{ python_min }}
    - fsspec>=0.7.5
    - httpx
    # httpx[http2]
    - h2 >=3,<5
    - authlib

tests:
  - python:
      python_version: ${{ python_min }}.*
      imports:
      - msgraphfs
      pip_check: true

about:
  homepage: https://github.com/acsone/msgraphfs
  summary: |
    A fsspec based filesystem-like interface to drives exposed through the
    Microsoft graph API (OneDrive, Sharepoint, etc).
  license: MIT
  license_file: LICENSE
  documentation: https://github.com/acsone/msgraphfs/blob/main/README.md
  repository: https://github.com/acsone/msgraphfs

extra:
  recipe-maintainers:
    - xylar
