{% set name = "album-docker" %}
{% set version = "0.2.0" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.org/packages/source/{{ name[0] }}/{{ name }}/album_docker-{{ version }}.tar.gz
  sha256: ae06c2f55049da0fca435eb396a26cdade946251ba98d14f580b93b4365759f3

build:
  noarch: python
  script: {{ PYTHON }} -m pip install . -vv --no-deps --no-build-isolation
  number: 0

requirements:
  host:
    - python >=3.7
    - pip
  run:
    - python >=3.7
    - album >=0.11.0,<0.13.0
    - docker-py

test:
  imports:
    - album
  commands:
    - pip check
  requires:
    - pip

about:
  home: https://gitlab.com/album-app/plugins/album-docker
  summary: album plugin for building docker images from solutions
  dev_url: https://gitlab.com/album-app/plugins/album-docker
  license: MIT
  license_file: LICENSE

extra:
  recipe-maintainers:
    - jpalbrecht
