{% set name = "nwb2bids" %}
{% set version = "0.4.0" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/{{ name }}-{{ version }}.tar.gz
  sha256: 69a70313d716f14bd8834aac6405dad8f47794f23a309ec4b6232d59dd0b984b

build:
  noarch: python
  script: {{ PYTHON }} -m pip install . -vv
  number: 0
  entry_points:
   - nwb2bids = nwb2bids._command_line_interface._main:_nwb2bids_cli

requirements:
  host:
    - python >=3.10
    - pip
  run:
    - python >=3.10
    - pandas
    - pynwb
    - click
    - pydantic
    - typing-extensions

test:
  requires:
    - pytest
    - pytest-cov
  source_files:
    - tests
  imports:
    - nwb2bids
  commands:
    - pytest

about:
  home: https://github.com/con/nwb2bids
  summary: Reorganize NWB files into a BIDS directory layout.
  description: |
    Currently developed for the microephys BIDS modality, which encompasses both the NWB ecephys and icephys
    neurodata subtypes, and which is currently pending formal inclusion in BIDS schema as part of BEP032.
  license: MIT
  license_family: MIT
  license_file: LICENSE.txt
  doc_url: https://con.github.io/nwb2bids/  # TODO: need to get this working before opening PR upstream
  dev_url: https://github.com/con/nwb2bids

extra:
  recipe-maintainers:
    - CodyCBakerPhD
    - yarikoptic
    - candleindark
    - asmacdo